### ISSUE TITLE
Pushbot Cordova Plugin Build Failed.

### ISSUE THREAD

**Issue by JijeshP** [pushbots/phonegap#8]
Using Plugins:
KJs-iMac:kaljacobs kaljacobs$ cordova plugin ls
android.support.v4 21.0.1 "Android Support v4"
com.pushbots.push 1.2.7 "Pushbots"
cordova-plugin-facebook4 1.1.0 "Facebook Connect"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-vibration 1.2.0 "Vibration"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova.plugin.googleplus 3.0.1 "Google+"
nl.x-services.plugins.socialsharing 4.3.18 "SocialSharing"
nl.x-services.plugins.toast 2.0.4 "Toast"
org.apache.cordova.network-information 0.2.15 "Network Information"

:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dexDebug'.
  
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  > /Developer/android/sdk/build-tools/23.0.0/dx --dex --no-optimize --output /Applications/XAMPP/xamppfiles/htdocs/android/kaljacobs/platforms/android/build/intermediates/dex/debug --input-list=/Applications/XAMPP/xamppfiles/htdocs/android/kaljacobs/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  > Error Code:
  >   2
  > Output:
  
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 37.238 secs

/Applications/XAMPP/xamppfiles/htdocs/android/kaljacobs/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Applications/XAMPP/xamppfiles/htdocs/android/kaljacobs/platforms/android/gradlew with args: cdvBuildDebug,-b,/Applications/XAMPP/xamppfiles/htdocs/android/kaljacobs/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /Applications/XAMPP/xamppfiles/htdocs/android/kaljacobs/platforms/android/cordova/run: Command failed with exit code 8

**Comment by JijeshP** [comment]
https://github.com/phonegap-build/PushPlugin/issues/573
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1028
https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032

**Comment by JijeshP** [comment]
@AbdullahDiaa @amrsobhy Conflict with https://github.com/Wizcorp/phonegap-facebook-plugin 
any solution ?

**Comment by JijeshP** [comment]
Updated Both plugin to "android-support-v13.jar" and that's works fine
